### ISSUE TITLE
英文版的 统一一下大小写和表述, 留一下空格

### ISSUE THREAD

**Issue by jjnnzb** [PowerJob/PowerJob-Console#11]
![image](https://user-images.githubusercontent.com/58833386/104093941-ca8b5d80-52c8-11eb-8bf0-35b992342836.png)
ContainerManager ---> Container Management, WorkflowManage ---> Workflow management等

**Comment by jjnnzb** [comment]
![1](https://user-images.githubusercontent.com/58833386/104095569-8604bf80-52d2-11eb-8293-5bc1b6fdfe2b.png)

**Comment by jjnnzb** [comment]
![2](https://user-images.githubusercontent.com/58833386/104096106-70dd6000-52d5-11eb-8a91-673a32b7b69e.png)

**Comment by jjnnzb** [comment]
![3](https://user-images.githubusercontent.com/58833386/104096621-f1509080-52d6-11eb-9547-8f56e2aa32df.png)

**Comment by jjnnzb** [comment]
![6](https://user-images.githubusercontent.com/58833386/104103163-8d7c9680-52db-11eb-9a25-79d760ec8468.png)

**Comment by KFCFans** [comment]
OK
