### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by JinyuZhang** [PowerJob/PowerJob-Console#51]
系统版本:debian-11.7
内核版本:5.10.0-23-amd64
系统类型:x86_64
node版本：18.16.1
npm版本：9.5.1

报错：npm ERR! code 1
npm ERR! path /home/app/docker/powerjob/powerjob-console/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.16.1 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` succeeded python2 /usr/bin/python2
npm ERR! gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 18.16.1
npm ERR! gyp verb command install [ '18.16.1' ]
npm ERR! gyp verb install input version string "18.16.1"
npm ERR! gyp verb install installing version: 18.16.1
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 18.16.1
npm ERR! gyp verb build dir attempting to create "build" dir: /home/app/docker/powerjob/powerjob-console/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /home/app/docker/powerjob/powerjob-console/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/app/docker/powerjob/powerjob-console/node_modules/node-sass/build/config.gypi
npm ERR! (node:542463) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: /home/app/docker/powerjob/powerjob-console/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/app/docker/powerjob/powerjob-console/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/app/docker/powerjob/powerjob-console/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.node-gyp/18.16.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/18.16.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/18.16.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/app/docker/powerjob/powerjob-console/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main

npm ERR!     options.duplicate_basename_check)
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
npm ERR!     params['parallel'], params['root_targets'])
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
npm ERR!     variables, includes, depth, check, True)
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
npm ERR!     includes, True, check)
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
npm ERR!     aux_data, includes, check)
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
npm ERR!     LoadOneBuildFile(include, data, aux_data, None, False, check),
npm ERR!   File "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
npm ERR!     None)
npm ERR!   File "/root/.node-gyp/18.16.1/include/node/common.gypi", line 1
npm ERR!     e_data_file_flag%': 1
npm ERR!                         ^
npm ERR! SyntaxError: EOL while scanning string literal
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.10.0-23-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/home/app/docker/powerjob/powerjob-console/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/app/docker/powerjob/powerjob-console/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.16.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-12T10_26_34_298Z-debug-0.log

/root/.npm/_logs/2023-07-12T10_26_34_298Z-debug-0.log日志：

[2023-07-12T10_26_34_298Z-debug-0.log](https://github.com/PowerJob/PowerJob-Console/files/12026823/2023-07-12T10_26_34_298Z-debug-0.log)

**Comment by ymms68** [comment]
node-sass install有问题

**Comment by ymms68** [comment]
node-sass install有问题，可以先再package.json去除node-sass, 再npm install, 然后单独install node-sass

**Comment by ymms68** [comment]
> node-sass install有问题，可以先再package.json去除node-sass, 再npm install, 然后单独install node-sass

npm install node-sass --sass-binary-site=https://npm.taobao.org/mirrors/node-sass -D

**Comment by KFCFans** [comment]
1.  node 版本降级为 v14.21.3
2. 删除原来的 node_modules，git reset --hard  HEAD 恢复 package.json
3. npm install
4. 理论上就好了

**Comment by itest6** [comment]
刚踩坑过来, 说下我的解决方案:

环境信息 

> OS: 	Ubuntu 20.04.4 LTS
> NodeJS: v14.21.3

1. apt-get install make g++ python2
2.  npm install --unsafe-perm  --registry=https://registry.npmmirror.com
